version: 2

models:
  - name: fact_prices_with_ta
    description: "Daily OHLCV with SMA(20/50), RSI(14), and daily return"
    columns:
      - name: symbol
        tests: [not_null]
      - name: dt
        tests: [not_null]
      